version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - lint-rust
      - build
      - test-rust:
          requires:
            - lint-rust
            - build
          matrix:
            parameters:
              db-mode: [ "single", "cluster" ]
              db-version: [ "3.10", "3.11", "3.12" ]

jobs:
  build:
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - run:
          name: Compile lightning
          command: cargo build --release

  lint-rust:
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - run:
          name: Install clippy
          command: rustup component add clippy
      - run:
          name: clippy
          command: cargo clippy -- -D warnings
      - run:
          name: fmt
          command: cargo fmt --all -- --check

  test-rust:
    parameters:
      db-mode:
        type: string
      db-version:
        type: string
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - run:
          name: Start Database
          command: ./docker/start_db.sh
          environment:
            STARTER_MODE: << parameters.db-mode >>
            DOCKER_IMAGE: docker.io/arangodb/arangodb:<< parameters.db-version >>
      - run:
          name: Cargo Test
          command: cargo test