name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Documentation
        run: cargo doc --no-deps

      - name: Clear docs folder
        run: rm -rf ./docs

      - name: Create index.html file manually
        run: echo '<meta http-equiv="refresh" content="0;url=arangors_graph_exporter/index.html">' > target/doc/index.html

      - name: Copy inner docs file to docs folder
        run: cp -r target/doc ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs